name: Fiji Imports
favicon: null
layout_spectrum: 0.22944895760156214
typography_spectrum: 0.66656
title: Fiji Imports
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#542f00'
    - '#96d348'
    - '#000000'
    - '#c2a580'
    - '#00ff00'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5974551611579955
  rhythmicContrast: 0.5
purpose: []
