name: Fiji Imports
favicon: null
layout_spectrum: 0.22944895760156214
typography_spectrum: 0.6979029283393174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8517207237891853
  lightness: 0.2767919839825481
  saturation: 0.5974551611579955
  rhythmicContrast: 0.7160447523929179
purpose: []
